---
- name: Install git packages
  apt:
    name: "{{item}}"
  with_items:
    - git

- name: Install git python packages
  pip:
    name: "{{item}}"
  with_items:
    - git-review

- name: template git config
  template:
    src: gitconfig
    dest: "~{{target_user}}/.gitconfig"
    owner: "{{target_user}}"
